name: pbdl
description: A starting point for Dart libraries or applications.
version: 2.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0"

dependencies:
  json_annotation: ^4.9.0
  hex: ^0.2.0
  quick_log: ^5.5.3
  http2: ^2.3.1
  path: ^1.9.1
  azblob: ^4.0.0
  recase: ^4.1.0
  archive: ^4.0.5
  meta: ^1.16.0
  uuid: ^4.5.1
  get_it: ^8.0.3

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  pedantic: ^1.11.1
  test: ^1.25.15
